data_opt:
    source: msd_task06
    start_pixdim: [0.785, 0.785, 1.25]
    target_scale_level: 2 # this has to correspond with inverse_scale_factors
    inverse_scale_factors: [[2,2,2],[2,2,2]]
    downsize_type: kspace # kspace, trilinear, nearest
    slide_depth: False # skip slide for downsampling depth-dimension
    preprop_intensity:
        type: minmax_range
        a_min: -1024
        a_max: 3000
        b_min: 0
        b_max: 1
    image_key: image
train_opt:
    batch_size: 1
    num_patch: 2
    patch_size: [96,96,96]
    max_epochs: 1000
    step_size: 100
    start_level: 0
model_opt:
    generator_type: dcsrn
    generator:
        spatial_dims: 3
        in_channels: 1
        out_channels: 1
        k: 24
        filter_size: 3
        num_units_per_block: 4
        bias: False
loss_opt:
    generator:
        pixel:
            params:
                loss_fn: l1
            loss_weight: 1