data_opt:
    source: hcp1200
    start_pixdim: [0.7,0.7,0.7]
    target_scale_level: 2 # this has to correspond with inverse_scale_factors
    inverse_scale_factors: [[2,2,2],[2,2,2]]
    downsize_type: kspace # kspace, trilinear, nearest
    slide_depth: False # skip slide for downsampling depth-dimension
    preprop_intensity:
        type: minmax
        minv: 0
        maxv: 1
    image_key: t2
train_opt:
    batch_size: 1
    num_patch: 2
    patch_size: [64,64,64]
    max_epochs: 1000
    step_size: 100
    start_level: 0
model_opt:
    generator_type: dcsrn
    discriminator_type: vgg_disc
    generator:
        spatial_dims: 3
        in_channels: 1
        out_channels: 1
        k: 24
        filter_size: 3
        num_units_per_block: 4
        bias: False
    discriminator:
        spatial_dims: 3
        num_in_ch: 1
        num_feat: 64
        input_size: [64,64,64]
loss_opt:
    generator:
        pixel:
            params:
                loss_fn: l1
            loss_weight: 1
        adv:
            params: {loss_fn: wgan}
            loss_weight: 0.01
    discriminator:
        disc:
            params: {loss_fn: wgan}
            loss_weight: 1
        